### ISSUE TITLE
Does this work with the MongoAPI-CosmosDB plugin?

### ISSUE THREAD

**Issue by luzlab** [hackolade/MongoDBCustomProperties#1]
The readme says this plugin works for Mongo, Couchbase, and DynamoDB, but doesn't mention CosmosDB.

**Comment by pdesmarets** [comment]
There's a plugin for each database target.  For the Cosmos DB with Mongo API, you can find it [here](https://github.com/hackolade/CosmosDB-with-Mongo-API).  However, I suggest you get it through the application via Help > DB Target Plugin Manager.

Let me know if you have any questions
